CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    FNAME VARCHAR2(100) NOT NULL,
    MNAME VARCHAR2(100),
    LNAME VARCHAR2(100),
    DOB DATE NOT NULL,
    CONTACTNO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL DEFAULT 'A'
);
CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT PRIMARY KEY,
    ACCOUNTNUMBER VARCHAR2(100) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(10) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    BRANCH_ID BIGINT NOT NULL,
    STATUS VARCHAR2(1) NOT NULL DEFAULT 'A'
);
CREATE TABLE CUSTOMER_ACCOUNT (
    CUSTOMER_X_ACCOUNT_ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    ACCOUNT_ID BIGINT,
    ROLE VARCHAR2(25) NOT NULL DEFAULT 'PRIMARY',
    CONSTRAINT FK_CA_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_CA_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID)
);

CREATE TABLE ACCOUNT_BALANCE (
    ACCOUNT_ID BIGINT PRIMARY KEY,
    LEDGER_BALANCE NUMERIC NOT NULL,
    AVAILABLE_BALANCE NUMERIC NOT NULL,
    HOLD_AMOUNT NUMERIC NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ACCOUNT_BALANCE
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID)
);
CREATE TABLE TRANSACTION (
    TRANSACTION_ID BIGINT PRIMARY KEY,
    ACCOUNT_ID BIGINT,
    AMOUNT NUMERIC NOT NULL,
    TYPE VARCHAR2(100) NOT NULL,
    TRANSACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRANSACTION
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT (ACCOUNT_ID)
);