CREATE SEQUENCE customer_seq
START WITH 1003
INCREMENT BY 1;

CREATE SEQUENCE account_seq
START WITH 20003
INCREMENT BY 1;

CREATE SEQUENCE customer_account_seq
START WITH 4
INCREMENT BY 1;

CREATE SEQUENCE transaction_seq
START WITH 3
INCREMENT BY 1;